### PR TITLE
More support at the parser level

### PR DESCRIPTION
**Pull request by charig**
Add support for:
- Literal Arrays: (Literal*)
- '--*' selectors

### CODE REVIEW

**Comment by smarr** [comment]
Hmm... what kind of selector is `--*`?

Also, this needs definitely some tests.
Could you add something to the core-lib, to make sure this really works?

**Comment by charig** [comment]
Sorry, --* is -- + validSelector, previously the prefix -- was not working and is valid in Smalltalk (there were some -- prefixes in gradual typing). 
Ok, i will add some tests.

**Comment by smarr** [comment]
Great, thanks, that would help me to port the changes also to the other variants.

**Comment by smarr** [comment]
Integrated with https://github.com/smarr/TruffleSOM/compare/50a482e...dee9150
and https://github.com/smarr/TruffleSOM/compare/0a97bf1...c278e9f

I also change the code style in some places to fit better with the surrounding code. Preferring implicit `this.` over explicit for instance. Your change is not really following the style of the existing code.

**Pull request closed without merging**
